# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/guitarrapc/github/guitarrapc/nativebuild-lab/zstd/build/cmake/programs/CMakeLists.txt))

/Users/guitarrapc/github/guitarrapc/nativebuild-lab/builder/zstd_ios/_builds/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.24.0/bin/cmake -H/Users/guitarrapc/github/guitarrapc/nativebuild-lab/zstd/build/cmake -B/Users/guitarrapc/github/guitarrapc/nativebuild-lab/builder/zstd_ios/_builds
