# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/guitarrapc/github/guitarrapc/nativebuild-lab/builder/zstd_ios/_builds/CMakeFiles/3.24.0/CMakeASMCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/guitarrapc/github/guitarrapc/nativebuild-lab/zstd/build/cmake/lib/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/guitarrapc/github/guitarrapc/nativebuild-lab/zstd/build/cmake/lib/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/guitarrapc/github/guitarrapc/nativebuild-lab/zstd/lib/libzstd.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/CMakeASMCompiler.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/CMakeASMInformation.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/CMakeCompilerIdDetection.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/CMakeDetermineASMCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/CMakeDetermineCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/CMakeFindBinUtils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/CMakeTestASMCompiler.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/Compiler/Clang-ASM.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/Compiler/Clang-FindBinUtils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/Compiler/Clang.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/Platform/Apple-Clang-ASM.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.0/share/cmake/Modules/Platform/Apple-Clang.cmake))

/Users/guitarrapc/github/guitarrapc/nativebuild-lab/builder/zstd_ios/_builds/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.24.0/bin/cmake -H/Users/guitarrapc/github/guitarrapc/nativebuild-lab/zstd/build/cmake -B/Users/guitarrapc/github/guitarrapc/nativebuild-lab/builder/zstd_ios/_builds
