@echo OFF
SETLOCAL ENABLEDELAYEDEXPANSION

set SCRIPT_DIR=%~dp0
call %SCRIPT_DIR%\settings.bat
set OS=windows
set ARCH=x64
set PLATFORM=x64
if not defined OUTPUT_DIR (set OUTPUT_DIR=pkg\%SRC_DIR%\%GIT_VERSION%\%OS%\%PLATFORM%)

:: build
call %SCRIPT_DIR%\core\builder-windows.bat
if %ERRORLEVEL% == 1 exit /b 1

:: confirm
dir %CMAKE_LIB%\*.lib
dir %CMAKE_LIB%\*.dll

:: copy
mkdir %OUTPUT_DIR%
cp %CMAKE_LIB%\%WIN_LIBNAME_CRYPTO%.dll .\%OUTPUT_DIR%\%WIN_LIBNAME_CRYPTO%.dll
cp %CMAKE_LIB%\%WIN_LIBNAME_CRYPTO%.lib .\%OUTPUT_DIR%\%WIN_LIBNAME_CRYPTO%.lib
cp %CMAKE_LIB%\%WIN_LIBNAME_TLS%.dll .\%OUTPUT_DIR%\%WIN_LIBNAME_TLS%.dll
cp %CMAKE_LIB%\%WIN_LIBNAME_TLS%.lib .\%OUTPUT_DIR%\%WIN_LIBNAME_TLS%.lib
cp %CMAKE_LIB%\%WIN_LIBNAME_X509%.dll .\%OUTPUT_DIR%\%WIN_LIBNAME_X509%.dll
cp %CMAKE_LIB%\%WIN_LIBNAME_X509%.lib .\%OUTPUT_DIR%\%WIN_LIBNAME_X509%.lib
