name: TOC Generator

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-24.04
    steps:
      - uses: technote-space/toc-generator@9e238e7974de5fcf7b17b7acc54c896160dda0a3 # v4.3.1
        with:
          MAX_HEADER_LEVEL: 2
          COMMIT_NAME: github-actions[bot]
          COMMIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
