name: zstd build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  OUTPUT_BASE: artifact

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        target: ["amd64", "arm64"]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: git fetch --tags
        working-directory: zstd
      - name: Build
        run: bash ./zstd-linux-${{ matrix.target }}.sh

  macos:
    strategy:
      fail-fast: false
      matrix:
        includes:
          - target: amd64
            runs-on: macos-latest
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: git fetch --tags
        working-directory: zstd
      - name: Build
        run: bash ./zstd-darwin.sh

  windows:
    strategy:
      fail-fast: false
      matrix:
        target: ["x64", "x86", "arm64"]
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: git fetch --tags
        working-directory: zstd
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: zstd-windows-${{ matrix.target }}-cmake.bat
        shell: cmd
